In [1]:
#list comprehensions:

nums = [0,1,2,3,4,5]
squares = [x**2 for x in nums]
print(squares)

[0, 1, 4, 9, 16, 25]


In [2]:
#Dictionaries

d = {'cat' : 'cute' , 'dog': 'furry'}
print(d['cat'])
print('cat' in d)
d['fish'] = 'wet'
print(d.get('monkey','N/A'))
print(d.get('fish','N/A'))
del d['fish']
print(d.get('fish','N/A'))

cute
True
N/A
wet
N/A


In [11]:
#Numpy Libribrary

import numpy as np

a = np.array([1,2,3])

print(type(a))
print(a.shape)

b = np.array([[1,2,3],[4,5,6]])
print(b.shape)

<class 'numpy.ndarray'>
(3,)
(2, 3)


In [16]:
a = np.zeros((2,2))
print(a)

b=np.ones((1,2))
print(b)

c = np.full((2,2),7)
print(c)

d = np.eye(2)
print("d:\n",d)

e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
d:
 [[1. 0.]
 [0. 1.]]
[[0.13587687 0.75147882]
 [0.15642896 0.97423675]]


In [20]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print("a:\n",a)
print("b:\n",b)

a:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
b:
 [[2 3]
 [6 7]]


In [21]:
# Product

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
